baseurl: ""
url: ""

# Build Settings
markdown: kramdown
permalink: pretty

# MathJax Configuration
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
  math_engine_opts:
    preview: true
    preview_as_code: true

# Simplified defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      mathjax: true

# Minimal theme settings
theme: null

# Basic includes
include:
  - "*.md"
  - "**/*.md"

exclude:
  - "node_modules"
  - ".git"
  - ".github"
  - "README.md"
  - Gemfile
  - Gemfile.lock
  - vendor
