baseurl: ""
url: ""

# Asset settings
sass:
  sass_dir: assets/css
  style: compressed

# Include these directories
include:
  - assets
  - "src/**/*.md"
exclude:
  - "node_modules"
  - ".git"
  - ".github"
  - "README.md"

theme: minima
# For using other GitHub-hosted themes, uncomment the following line:
# remote_theme: pages-themes/cayman
